pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=Cloudflare Pages"
    actions:
      comment:
        message: "Merged by the rule: Automatic merge commit from Dependabot"
  - name: automatic merge for bot
    conditions:
        - "label=Automated PR"
        - "check-success=Cloudflare Pages"
    actions:
      merge:
        method: merge
      comment:
        message: "Merged by the rule: Merge main to pages"
      delete_head_branch:
        force: true
