pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - "check-success=Cloudflare Pages"
    actions:
      comment:
        message: Hi, I will automerge this as you are Dependabot, go ahead ! :p
      merge:
        method: merge